enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
included-patches = "'Permanent repeat'"
excluded-patches = "'Spoof client'"

[YouTube]
version = "auto"
build-mode = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Swipe controls' 'Hide related video overlay' 'Hide timestamp' 'Custom player overlay opacity' 'Wide search bar' 'Open Shorts in regular player' 'Spoof app version' 'Change start page' 'Theme' 'Alternative thumbnails' 'Bypass image region restrictions' 'Spoof device dimensions' 'Check watch history domain name resolution' 'Spoof video streams'"
